#:kivy 2.3.0
<CircleArea>:
    Label:
        text: "Radius (cm):"
        pos: 5, self.parent.top - 100
    TextInput:
        id: radius
        multiline: False
        pos: 100, self.parent.top - 63.5
        on_text: root.calculate_area()
        size: 100, 25
        font_size: 10
    Label:
        text: "Area:"
        pos: 5, self.parent.top - 125
    Label:
        id: area
        pos: 100, self.parent.top - 125